<?php

$fr = array(
	//French language of home page index.php
	//============================================================================================================================================================================================================================================================================================================================================================================================================
	"nav-home" => "Accueil",
	"nav-about" => "A propos",
	"nav-service" => "Nos services",
	"nav-contact" => "Nous contacter",
	"lang-fr" => "Français",
	"lang-ang" => "Anglais",
	"lang-es" => "Espagnole",
	//background and banner
	"banner1-h6" => "Harmonie",
	"banner1-h4-1" => "Du grec ancien,",
	"banner1-h4-2" => "‘Harmonia’",
	"banner1-p" => "Green Planet Communication prend le temps d’écouter votre mode de fonctionnement et se met au diapason de vos valeurs. Nous portons ensuite votre voix au sein de votre entreprise et au coeur de votre marché.",
	"banner1-btn" => "Nous contacter",
	"banner2-h6" => "Excellence",
	"banner2-h4-1" => "Du latin excellentia,",
	"banner2-h4-2" => "‘surpassement’",
	"banner2-p" => "Nous analysons votre positionnement et votre avantage concurrentiel pour déterminer la stratégie gagnante. Nous la traduisons dans un plan opérationnel efficace et en assurons une diffusion pertinente.",
	"banner2-btn" => "Nos services",
	"banner3-h6" => "Fiabilité",
	"banner3-h4-1" => "Du latin fidere,",
	"banner3-h4-2" => "‘avoir confiance’",
	"banner3-p" => "Concentrez-vous sur votre métier. Développez vos idées. Exploitez votre expertise. Nous nous occupons de les mettre en valeur, en toute confiance.",
	"banner3-btn" => "Apprendre plus",
	"banner4-h6" => "Durabilité",
	"banner4-h4-1" => "Resister",
	"banner4-h4-2" => " aux effets du temps",
	"banner4-p" => "Nous aimons frapper un grand coup pour propulser votre message au premier plan. Mais ce que nous préférons par dessus tout, c’est l’ancrer durablement dans les esprits.",
	"banner4-btn" => "Apprendre plus",	
	"slogan" => "Propulsez durablement vos idées.",
	//about
	"about-span" => "Qui sommes-nous?",
	"about-h2" => "A la découverte de ",
	"about-h2-em" => "notre entreprise",
	"about-p" => "Notre mission est de transformer la communication de votre entreprise en vecteur de croissance durable.",
	"about-btn" => "Découvrir",
	//testimonial
	"testimonial-h2" => "Ce qu'on dit ",
	"testimonial-h2-em" => "à propos de nous",
	"testimonial-span" => "Les avis de nos plus grands clients",
	//footer
	// reseaux sociaux
	"footer1-h4" => "Nos réseaux sociaux",
	"footer1-p" => "En cliquant sur ces icones, vous allez être redirigé directement vers nos réseaux sociaux.<",
	// useful links
	"footer2-h4" => "Liens utiles",
	"footer2-link1" => "Retour en haut de la page",
	"footer2-link2" => "Nos services",
	"footer2-link3" => "Découvrir notre entreprise",
	"footer2-link4" => "Les avis sur nous",
	"footer2-link5" => "Nos partenaires",
	// Additional pages
	"footer3-h4" => "Pages supplémentaires",
	"footer3-link1" => "A propos",
	"footer3-link2" => "Nous contacter",
	"footer3-link3" => "Page d'aide",
	"footer3-link4" => "Politique de confidentialité",
	// send message (mail)
	"footer4-h4" => "Nous contacter",
	"footer4-placeholder-fullname" => "Nom complet",
	"footer4-placeholder-mailAdress" => "Adresse mail",
	"footer4-placeholder-message" => "Votre message",
	//home page ends here 
	//============================================================================================================================================================================================================================================================================================================================================================================================================
	
	//French language of about page abo.php
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
)
	
?>